
export const ALL_CITIES = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Tirupati",
    "Kadapa",
    "Kakinada",
    "Anantapur",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Roing",
    "Tezu",
    "Ziro",
    "Bomdila",
    "Tawang",
    "Along",
    "Yingkiong",
  ],
  Assam: [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Karimganj",
    "Sibsagar",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Bihar Sharif",
    "Arrah",
    "Begusarai",
    "Katihar",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Durg",
    "Raigarh",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Dhamtari",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Sanquelim",
    "Curchorem",
    "Cuncolim",
    "Sanguem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Nadiad",
    "Anand",
  ],
  Haryana: [
    "Faridabad",
    "Gurgaon",
    "Hisar",
    "Rohtak",
    "Panipat",
    "Karnal",
    "Sonipat",
    "Yamunanagar",
    "Panchkula",
    "Ambala",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Solan",
    "Dharamshala",
    "Mandi",
    "Palampur",
    "Hamirpur",
    "Una",
    "Kullu",
    "Chamba",
    "Bilaspur",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Phusro",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
  ],
  Karnataka: [
    "Bangalore (Bengaluru)",
    "Mysore (Mysuru)",
    "Hubli-Dharwad",
    "Mangalore",
    "Belgaum",
    "Gulbarga",
    "Davanagere",
    "Bellary",
    "Bijapur",
    "Shimoga",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi (Cochin)",
    "Kozhikode (Calicut)",
    "Thrissur",
    "Kollam (Quilon)",
    "Kannur",
    "Kottayam",
    "Alappuzha (Alleppey)",
    "Palakkad",
    "Malappuram",
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Aurangabad",
    "Navi Mumbai",
    "Solapur",
  ],
  Manipur: [
    "Imphal",
    "Thoubal",
    "Kakching",
    "Mayang Imphal",
    "Wangjing",
    "Lilong",
    "Yairipok",
    "Moirang",
    "Bishnupur",
    "Lamlai",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongstoin",
    "Williamnagar",
    "Baghmara",
    "Jowai",
    "Resubelpara",
    "Khliehriat",
    "Mairang",
    "Cherrapunji",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Saiha",
    "Thenzawl",
    "Kolasib",
    "Serchhip",
    "Mamit",
    "Lawngtlai",
    "Hnahthial",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Mon",
    "Phek",
    "Longleng",
    "Kiphire",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Brahmapur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
  ],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Pathankot",
    "Moga",
    "Batala",
    "Abohar",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sikar",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Mangan",
    "Jorethang",
    "Singtam",
    "Rangpo",
    "Gyalshing",
    "Lachung",
    "Pakyong",
    "Chungthang",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Mancherial",
    "Adilabad",
    "Siddipet",
  ],
  Tripura: [
    "Agartala",
    "Dharmanagar",
    "Udaipur",
    "Belonia",
    "Kailasahar",
    "Ambassa",
    "Kamalpur",
    "Santirbazar",
    "Ranirbazar",
    "Sonamura",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Meerut",
    "Varanasi",
    "Allahabad",
    "Bareilly",
    "Aligarh",
    "Moradabad",
  ],
};

export const CHARGING_PLUGS = [
  "CHAdeMO",
  "CCS",
  "EV charging connector types",
  "Type 2 connector",
  "Ccs combo 1 ev charging plug",
  "J1772 connector type 1",
  "Socketed charger",
  "Tesla connectors",
  "Type 1",
];
